# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('endings', models.CharField(default=b'0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0', max_length=35)),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Ativado')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_played', models.DateTimeField(auto_now_add=True)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='SaveSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_started', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('current_chapter', models.SmallIntegerField(default=1)),
                ('events', models.ManyToManyField(to='book.Event')),
                ('inventory', models.ManyToManyField(to='book.Item')),
                ('player_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_slots', to='player.Player')),
                ('progress', models.ManyToManyField(through='player.Progress', to='book.Paragraph')),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='save_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_save_slot', to='player.SaveSlot'),
        ),
        migrations.AddField(
            model_name='player',
            name='active_save_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SaveSlot'),
        ),
    ]
