# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='events_required_not_to_have',
            new_name='excluding_events',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='items_required_not_to_have',
            new_name='excluding_items',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='events_required_to_have',
            new_name='required_events',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='items_required_to_have',
            new_name='required_items',
        ),
    ]
