# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20160221_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='excluding_events',
            field=models.ManyToManyField(blank=True, related_name='excludes_option', to='book.Event'),
        ),
        migrations.AlterField(
            model_name='option',
            name='excluding_items',
            field=models.ManyToManyField(blank=True, related_name='excludes_option', to='book.Item'),
        ),
        migrations.AlterField(
            model_name='option',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Paragraph'),
        ),
        migrations.AlterField(
            model_name='option',
            name='required_events',
            field=models.ManyToManyField(blank=True, related_name='enables_option', to='book.Event'),
        ),
        migrations.AlterField(
            model_name='option',
            name='required_items',
            field=models.ManyToManyField(blank=True, related_name='enables_option', to='book.Item'),
        ),
        migrations.AlterField(
            model_name='option',
            name='target',
            field=models.PositiveIntegerField(),
        ),
    ]
